name: Python Deneme

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Python Version
        run: python --version
      - name: Run Pip Version
        run: pip --version
