name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Flit
        run: |
          pip install flit
      - name: Install Dependencies
        run: flit install --symlink
      - name: Install Thundra Python Agent
        uses: thundra-io/thundra-foresight-python-action@v1
        with:
          apikey: ${{ secrets.THUNDRA_APIKEY }}
          project_id: ${{ secrets.THUNDRA_PROJECT_ID }}
          test_disable: false
          agent_version: 3.0.0
      - name: Test
        run: |
          pip install pytest-parallel
          bash scripts/test.sh
        env:
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.me/v1
          THUNDRA_AGENT_DEBUG_ENABLE: true
      - name: Upload coverage
        uses: codecov/codecov-action@v1
